<h1>Сайты</h1>

<?php if (!empty($flash)): ?>
<p style="color: green"><?= $flash['success'][0] ?></p>
<?php endif; ?>
<?php if (empty($urls)): ?>
<p>Nothing to display, sorry. :(</p>
<?php endif; ?>
<div class="table-responsive">
  <table class="table table-bordered table-hover text-nowrap" data-test="urls">
    <thead>
      <tr>
        <th>ID</th>
        <th>Имя</th>
        <th>Последняя проверка</th>
        <th>Код ответа</th>
      </tr>
    </thead>
    <tbody>
      <?php foreach ($urls as $urlData): ?>
      <tr>
        <td><?= $urlData['url']->getId() ?></td>
        <td><a href="/urls/<?= $urlData['url']->getId() ?>"><?= htmlspecialchars($urlData['url']->getName()) ?></a></td>
        <td><?= $urlData['lastCheck'] ? $urlData['lastCheck']['created_at'] : '' ?></td>
        <td><?= $urlData['lastCheck'] ? $urlData['lastCheck']['status_code'] : '' ?></td>
      </tr>
      <?php endforeach; ?>
    </tbody>
  </table>
</div>