<div class="table-responsive">
  <h1>Сайт: <?= htmlspecialchars($url->getName()) ?></h1>
  <table class="table table-bordered table-hover text-nowrap">
    <tbody>
      <tr>
        <td>ID</td>
        <td><?= $url->getId() ?></td>
      </tr>
      <tr>
        <td>Имя</td>
        <td><?= htmlspecialchars($url->getName()) ?></td>
      </tr>
      <tr>
        <td>Дата создания</td>
        <td><?= htmlspecialchars($url->getDate()) ?></td>
      </tr>
    </tbody>
  </table>
</div>
<h2 class="mt-5 mb-3">Проверки</h2>
<form class="mb-2" method="post" action="/urls/<?= $url->getId() ?>/checks">
  <input type="submit" class="btn btn-primary" value="Запустить проверку" name="url[id]">
</form>

<table class="table table-bordered table-hover" data-test="checks">
  <thead>
    <tr>
      <th>ID</th>
      <th>Код ответа</th>
      <th>h1</th>
      <th>title</th>
      <th>description</th>
      <th>Дата создания</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach ($checks as $check): ?>
      <tr>
        <td><?= $check->getId() ?></td>
        <td><?= $check->getStatus() ?></td>
        <td class="text-break"><?= $check->getH1() ?></td>
        <td class="text-break"><?= $check->getTitle() ?></td>
        <td class="text-break"><?= $check->getMeta() ?></td>
        <td><?= $check->getDate() ?></td>
      </tr>
    <?php endforeach; ?>
  </tbody>
</table>
